<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-JobNexus.Worker-61f18daa-a98e-450c-bad1-c4959609e51c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobNexus.Core\JobNexus.Core.csproj" />
    <ProjectReference Include="..\JobNexus.Storage\JobNexus.Storage.csproj" />
  </ItemGroup>
</Project>
